services:
  - type: web
    name: moggerai-discord-bot
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GEMINI_API_KEY_1
        sync: false
      - key: GEMINI_API_KEY_2
        sync: false
      - key: GEMINI_API_KEY_3
        sync: false
      - key: GROQ_API_KEY_1
        sync: false
      - key: GROQ_API_KEY_2
        sync: false
      - key: WEB_PORT
        value: 5000
